# Generated by Django 3.1.2 on 2020-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20201013_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(blank=True, choices=[('4', '2021'), ('3', '2022'), ('2', '2023'), ('1', '2024')], max_length=30, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Student ID'),
        ),
    ]
