# Generated by Django 3.1.2 on 2020-10-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20201013_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'verbose_name': 'Study Group'},
        ),
    ]
