# Generated by Django 3.1.2 on 2020-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20201110_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='groupme_option',
            field=models.BooleanField(default=False, verbose_name='Create GroupMe?'),
        ),
    ]
