# Generated by Django 3.1.2 on 2020-11-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_profile_slug'),
        ('study', '0008_auto_20201110_1112'),
    ]

    operations = [
    ]
