# Generated by Django 3.1.2 on 2020-11-11 00:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('study', '0009_merge_20201110_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=taggit.managers.TaggableManager(help_text='ex: CS1110, ECON1010', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
